spring:
  application:
    name: JobRecruitmentPlatform-Server
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jrp?stringtype=unspecified}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:niggamove}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: BotCV
          secret-key: ${JWT_SECRET:7d38bb48b74cc00cfe9b83171c52042abc4a4eec296217f154ae2d810d070879}
          access-token:
            expiration: 600000
          refresh-token:
            expiration: 604800000
      client:
        registration:
          google:
            client-id: ${CLIENT_ID:3503765693-1jivvacrfg59brqfdd7gm0imfv25r8ge.apps.googleusercontent.com}
            client-secret: ${CLIENT_SECRET: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}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:hocongtoan987@gmail.com}
    password: ${MAIL_PASSWORD:vaug kzao cxdl uxte}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
